"""Visualization script for Quantum Transfer Learning metrics on NIfTI data.

This script parses the serialized evaluation metrics JSON generated by
`scripts/nifti/metrics/evaluate_qtl.py`, dynamically detects the
top-performing QTL model run, and produces publication-quality charts
(metric boxplots, comparative ROC curves, isolated ROC curve for the best
run, and confusion matrix heatmap).
"""

import json
import os
import sys

from dementia_boost.telemetry.logger import setup_logger
from dementia_boost.telemetry.visualizer import MetricsVisualizer


def get_optimal_run_id(results_json_path: str) -> str:
    """Identifies the best-performing model run based on accuracy and AUC.

    Args:
        results_json_path: Filepath to the serialized QTL results JSON.

    Returns:
        The run_id string of the highest performing run.

    Raises:
        ValueError: If no individual runs are present in the JSON payload.
    """
    with open(results_json_path) as file:
        data = json.load(file)

    runs = data.get("individual_runs", [])
    if not runs:
        raise ValueError("No individual runs found in results JSON.")

    best_run = max(
        runs,
        key=lambda item: (
            float(item.get("accuracy", 0.0)),
            float(item.get("auc", 0.0)),
        ),
    )
    return str(best_run["run_id"])


def main() -> None:
    """Generates all visualization artifacts for QTL NIfTI models."""
    logger = setup_logger("visualize_qtl_nifti")

    results_json_path = "./data/results/metrics/nifti/qtl_results.json"
    plots_output_dir = "./data/results/plots/nifti/qtl"

    if not os.path.exists(results_json_path):
        logger.error(f"Results file not found at: {results_json_path}")
        logger.error("Please execute scripts/nifti/metrics/evaluate_qtl.py first.")
        sys.exit(1)

    logger.info(f"Initializing Visualizer. Output directory: {plots_output_dir}")
    visualizer = MetricsVisualizer(output_dir=plots_output_dir)

    try:
        optimal_run_id = get_optimal_run_id(results_json_path)
        logger.info(
            f"Identified top-performing run for isolated plots: {optimal_run_id}"
        )

        logger.info("Generating Metric Distributions Box Plot...")
        visualizer.plot_metric_distributions(results_json_path, prefix="qtl")

        logger.info("Generating Comparative ROC Curves...")
        visualizer.plot_comparative_roc(results_json_path, prefix="qtl")

        logger.info(f"Generating Isolated ROC Curve for {optimal_run_id}...")
        visualizer.plot_isolated_roc(
            results_json_path,
            run_id=optimal_run_id,
            prefix="qtl",
        )

        logger.info(f"Generating Confusion Matrix Heatmap for {optimal_run_id}...")
        visualizer.plot_confusion_matrix(
            results_json_path,
            run_id=optimal_run_id,
            prefix="qtl",
        )

        logger.info("Success! All QTL visualizations have been generated.")
    except Exception as error:
        logger.error(f"Failed to generate plots: {error}")
        sys.exit(1)


if __name__ == "__main__":
    main()
