"""Data loading pipelines and custom normalization transforms for OASIS-2 datasets.

This module provides the `OasisDataLoader` factory class to instantiate PyTorch
`DataLoader` objects for both serialized NIfTI slice tensors and 2D JPG images,
applying appropriate resizing, augmentation, and min-max normalization pipelines.
"""

import csv
import os
from typing import Any, Literal

import torch
from torch import Tensor
from torch.utils.data import DataLoader
from torchvision import transforms

from dementia_boost.data.dataset import JpgOasisDataset, OasisDataset

DataMode = Literal["nifti", "jpg"]


class OasisDataLoader:
    """Unified data loader factory for NIfTI tensors and JPG image pipelines.

    The class automatically selects the appropriate dataset class and torchvision
    transforms based on the specified mode, and loads data from pre-processed
    serialized tensors (`.pt`) or CSV indexes generated by the indexing pipeline.

    Attributes:
        RESULTS_PATH: Base directory where processed data and indexes are stored.
            Defaults to "./data/results".
    """

    RESULTS_PATH = "./data/results"

    def __init__(self, batch_size: int = 4, mode: DataMode = "nifti") -> None:
        """Initializes the loader with the specified batch size and data mode.

        Args:
            batch_size: The number of samples per batch to load. Defaults to 4.
            mode: Specifies the target data pipeline to use. Must be either
                "nifti" or "jpg". Defaults to "nifti".
        """
        self._batch_size = batch_size
        self._mode = mode

    def get_data_loader(self, is_train: bool = True) -> DataLoader:
        """Creates and returns a PyTorch DataLoader for the specified subset.

        The method selects the dataset implementation based on `self._mode`:
        - For "nifti", loads pre-processed `.pt` tensor files from
          `RESULTS_PATH/train/` or `RESULTS_PATH/test/`.
        - For "jpg", reads a CSV index file (`train_jpg_index.csv` or
          `test_jpg_index.csv`) created by `JpgDataIndexer`.

        Args:
            is_train: If True, loads the training set; otherwise, loads the test
                set. Defaults to True.

        Returns:
            A PyTorch DataLoader configured with the appropriate dataset, batch
            size, shuffling, and memory pinning.

        Raises:
            FileNotFoundError: If the required data files (NIfTI `.pt` files or
                JPG CSV index) do not exist at the expected location.
        """
        use_pin_memory = torch.cuda.is_available() or torch.backends.mps.is_available()

        if self._mode == "nifti":
            dir_name = "train" if is_train else "test"
            dir_path = os.path.join(self.RESULTS_PATH, dir_name)

            if not os.path.exists(dir_path) or not os.listdir(dir_path):
                raise FileNotFoundError(
                    f"Processed NIfTI data not found at {dir_path}. "
                    "Run OasisDataProcessor().process_and_save() first."
                )

            dataset = OasisDataset(
                directory_path=dir_path,
                transform=self._get_nifti_transform(),
            )

            return DataLoader(
                dataset,
                batch_size=self._batch_size,
                shuffle=is_train,
                pin_memory=use_pin_memory,
            )
        else:  # "jpg" mode
            csv_name = (
                "jpg/train_jpg_index.csv" if is_train else "jpg/test_jpg_index.csv"
            )
            csv_path = os.path.join(self.RESULTS_PATH, csv_name)

            if not os.path.exists(csv_path):
                raise FileNotFoundError(
                    f"JPG index target missing: {csv_path}. Run indexer pipeline first."
                )

            samples: list[tuple[str, int]] = []
            with open(csv_path) as f:
                reader = csv.reader(f)
                next(reader)
                for row in reader:
                    if row:
                        samples.append((row[0], int(row[1])))

            jpg_dataset = JpgOasisDataset(
                samples=samples,
                transform=self._get_jpg_transform(is_train=is_train),
            )

            return DataLoader(
                jpg_dataset,
                batch_size=self._batch_size,
                shuffle=is_train,
                pin_memory=use_pin_memory,
            )

    def _get_nifti_transform(self) -> transforms.Compose:
        """Defines the transformation pipeline for raw NIfTI float tensors.

        The pipeline consists of:
        1. Resizing to 128x128 pixels (with antialiasing enabled).
        2. Min-max normalization to [0.0, 1.0] (per-image).
        3. Standard normalization with mean=0.5 and std=0.5 to map to [-1.0, 1.0].

        Returns:
            A composed torchvision transform pipeline.
        """
        return transforms.Compose(
            [
                transforms.Resize((128, 128), antialias=True),
                MinMaxNormalize(),
                transforms.Normalize(mean=[0.5], std=[0.5]),
            ]
        )

    def _get_jpg_transform(self, is_train: bool) -> transforms.Compose:
        """Defines the transformation pipeline for JPG images.

        The pipeline includes:
        1. Resizing to 128x128 pixels.
        2. Random horizontal flip (applied only during training).
        3. Conversion to tensor.
        4. Normalization with mean=0.45 and std=0.5.

        Args:
            is_train: If True, adds data augmentation (random horizontal flip)
                to the transform list.

        Returns:
            A composed torchvision transform pipeline.
        """
        transform_list: list[Any] = [
            transforms.Resize((128, 128)),
        ]

        if is_train:
            transform_list.append(
                transforms.RandomHorizontalFlip(),
            )

        transform_list.extend(
            [
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.45], std=[0.5]),
            ]
        )

        return transforms.Compose(transform_list)


class MinMaxNormalize:
    """Transform that scales medical image tensors dynamically to [0.0, 1.0].

    This transform operates on a per-image basis (per-sample scaling) to preserve
    local tissue contrast. If the dynamic range is negligible (< 1e-6), the
    input tensor is returned unchanged to prevent division by zero.
    """

    def __call__(self, tensor: Tensor) -> Tensor:
        """Applies min-max scaling to the input tensor.

        Args:
            tensor: Input image tensor of arbitrary dimensions.

        Returns:
            Scaled tensor with values normalized to [0.0, 1.0] if dynamic range
            permits; otherwise, the original tensor.
        """
        min_val = tensor.min()
        max_val = tensor.max()

        if max_val - min_val > 1e-6:
            return (tensor - min_val) / (max_val - min_val)
        return tensor
