import csv
import os
from typing import Any, Literal

import torch
from torch import Tensor
from torch.utils.data import DataLoader
from torchvision import transforms

from dementia_boost.data.dataset import JpgOasisDataset, OasisDataset

DataMode = Literal["nifti", "jpg"]


class OasisDataLoader:
    """
    Unified Data Management interface providing PyTorch DataLoaders for both
    high-fidelity NIfTI tensors and down-sampled target JPG pipelines.
    Applies resizing and normalization transforms.

    The class automatically selects the appropriate dataset class and transforms
    based on the specified mode, and loads data from pre‑processed files or
    CSV indexes generated by the indexer.

    Attributes:
        RESULTS_PATH (str): Base directory where processed data are stored.
        Defaults to "./data/results".
    """

    RESULTS_PATH = "./data/results"

    def __init__(self, batch_size: int = 4, mode: DataMode = "nifti") -> None:
        """
        Initializes the loader with specified batch size and data mode.

        Args:
            batch_size (int): The number of samples per batch to load.
                Defaults to 4.
            mode (DataMode): Specifies the target data pipeline to use.
                Must be either "nifti" or "jpg". Defaults to "nifti".
        """
        self._batch_size = batch_size
        self._mode = mode

    def get_data_loader(self, is_train: bool = True) -> DataLoader:
        """
        Creates and returns a DataLoader for the specified subset.

        The method chooses the dataset implementation based on `self._mode`:
        - For "nifti", it expects pre‑processed .pt files in `RESULTS_PATH/train/`
          or `RESULTS_PATH/test/` generated by `OasisDataProcessor`.
        - For "jpg", it reads a CSV index file (`train_jpg_index.csv` or
          `test_jpg_index.csv`) created by `JpgDataIndexer`.

        Args:
            is_train (bool): If True, loads the training set; otherwise, loads
                the test set. Defaults to True.

        Returns:
            DataLoader: A PyTorch DataLoader configured with the appropriate
            dataset, batch size, shuffle, and pin_memory
            if a GPU/Apple Metal is available.

        Raises:
            FileNotFoundError: If the required data files (NIfTI .pt files or
                JPG CSV index) do not exist at the expected location.
        """
        use_pin_memory = torch.cuda.is_available() or torch.backends.mps.is_available()

        if self._mode == "nifti":
            dir_name = "train" if is_train else "test"
            dir_path = os.path.join(self.RESULTS_PATH, dir_name)

            if not os.path.exists(dir_path) or not os.listdir(dir_path):
                raise FileNotFoundError(
                    f"Processed NIfTI data not found at {dir_path}. "
                    "Run OasisDataProcessor().process_and_save() first."
                )

            dataset = OasisDataset(
                directory_path=dir_path,
                transform=self._get_nifti_transform(),
            )

            return DataLoader(
                dataset,
                batch_size=self._batch_size,
                shuffle=is_train,
                pin_memory=use_pin_memory,
            )
        else:  # "jpg" mode
            csv_name = (
                "jpg/train_jpg_index.csv" if is_train else "jpg/test_jpg_index.csv"
            )
            csv_path = os.path.join(self.RESULTS_PATH, csv_name)

            if not os.path.exists(csv_path):
                raise FileNotFoundError(
                    f"JPG index target missing: {csv_path}. Run indexer pipeline first."
                )

            samples: list[tuple[str, int]] = []
            with open(csv_path) as f:
                reader = csv.reader(f)
                next(reader)
                for row in reader:
                    if row:
                        samples.append((row[0], int(row[1])))

            jpg_dataset = JpgOasisDataset(
                samples=samples,
                transform=self._get_jpg_transform(is_train=is_train),
            )

            return DataLoader(
                jpg_dataset,
                batch_size=self._batch_size,
                shuffle=is_train,
                pin_memory=use_pin_memory,
            )

    def _get_nifti_transform(self) -> transforms.Compose:
        """
        Defines the sequence of image transformations for raw NIfTI float tensors.

        The pipeline consists of:
        1. Resizing to 128x128 pixels (with antialiasing).
        2. Min‑max normalization to [0, 1] (per‑image).
        3. Standard normalization with mean=0.5 and std=0.5 to map to [-1, 1].

        Returns:
            transforms.Compose: A composed torchvision transform.
        """
        return transforms.Compose(
            [
                transforms.Resize((128, 128), antialias=True),
                MinMaxNormalize(),
                transforms.Normalize(mean=[0.5], std=[0.5]),
            ]
        )

    def _get_jpg_transform(self, is_train: bool) -> transforms.Compose:
        """
        Defines the sequence of image transformations for JPG images.

        The pipeline includes:
        1. Resizing to 64x64 pixels.
        2. Random horizontal flip (only during training).
        3. Conversion to tensor.
        4. Normalization with mean=0.45 and std=0.5.

        Args:
            is_train (bool): If True, adds data augmentation (random flip)
                to the transform list.

        Returns:
            transforms.Compose: A composed torchvision transform.
        """
        transform_list: list[Any] = [
            transforms.Resize((64, 64)),
        ]

        if is_train:
            transform_list.append(
                transforms.RandomHorizontalFlip(),
            )

        transform_list.extend(
            [
                transforms.ToTensor(),
                transforms.Normalize(mean=[0.45], std=[0.5]),
            ]
        )

        return transforms.Compose(transform_list)


class MinMaxNormalize:
    """
    Custom transform to scale unbounded medical image tensors to the [0.0, 1.0] range.

    This transform operates on a per‑image basis (global per‑sample scaling)
    to preserve local contrast. If the image range is extremely small, the
    tensor is returned unchanged to avoid division by zero.

    The transform is designed for 2D or 3D tensors and assumes no batch dimension.
    """

    def __call__(self, tensor: Tensor) -> Tensor:
        """
        Applies min‑max scaling to the input tensor.

        Args:
            tensor (Tensor): Input tensor of arbitrary shape.

        Returns:
            Tensor: Scaled tensor with values in [0.0, 1.0] if the range is
            sufficiently large; otherwise, the original tensor is returned.
        """
        min_val = tensor.min()
        max_val = tensor.max()

        if max_val - min_val > 1e-6:
            return (tensor - min_val) / (max_val - min_val)
        return tensor
